name: library
description: A new Flutter package project.
publish_to: "none"
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
